language: csharp
sudo: true
dist: xenial
mono: none
dotnet: 2.2
before_install:
  - bash <(curl -fsSL https://raw.githubusercontent.com/PowerShell/PowerShell/v6.1.1/tools/install-powershell.sh)
script:
  - ./build.ps1
branches:
  only:
    - master
    - develop
    - travis
    - /^feature\/.*/
